apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: jboss-eap7-with-postgres
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    capability.openshift.io/name: Console
spec:
  description: 'Deploy a JBoss EAP 7 application to connect to a PostgreSQL database'
  displayName: Connect JBoss EAP 7 to a PostgreSQL database
  durationMinutes: 15
  icon: >-
    data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMDt9LmNscy0ye2ZpbGw6I2MyMWEwMDt9LmNscy0ze2ZpbGw6I2NkY2RjZDt9LmNscy00e2ZpbGw6I2I3YjdiNzt9LmNscy01e2ZpbGw6I2VhZWFlYTt9LmNscy02e2ZpbGw6I2ZmZjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkxvZ288L3RpdGxlPjxnIGlkPSJMYXllcl8xIiBkYXRhLW5hbWU9IkxheWVyIDEiPjxjaXJjbGUgY2xhc3M9ImNscy0xIiBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0yMC43MSA1MCkgcm90YXRlKC00NSkiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik04NS4zNiwxNC42NEE1MCw1MCwwLDAsMSwxNC42NCw4NS4zNloiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik02MC4xNyw0My4xM2EzLjQxLDMuNDEsMCwwLDEsLjA3LjY4QTMuNCwzLjQsMCwwLDAsNjAuMTcsNDMuMTNaIi8+PHBhdGggY2xhc3M9ImNscy0zIiBkPSJNNTkuMjEsNDEuMzhBMy40OCwzLjQ4LDAsMCwxLDYwLDQyLjQ3LDMuNDgsMy40OCwwLDAsMCw1OS4yMSw0MS4zOFoiLz48cG9seWdvbiBjbGFzcz0iY2xzLTMiIHBvaW50cz0iNTkuMTMgNDEuMjkgNTkuMTMgNDEuMjkgNTkuMDQgNDEuMjEgNTkuMTMgNDEuMjkiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik01OS4xMiw0Ni4zNCwzMy41NCw2OS43M2wyNS41OC0yMy40YTMuNDUsMy40NSwwLDAsMCwuOTEtMS40QTMuNDUsMy40NSwwLDAsMSw1OS4xMiw0Ni4zNFoiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik0yOC41NCw3MS40OCw1OC44Nyw0MSw1OC43OSw0MWEzLjcsMy43LDAsMCwwLTUuMjEuMkwyOSw2OC4yNmMtMSwxLTEuMTksMi41Mi0uMzUsMy4zMWExLjc1LDEuNzUsMCwwLDAsLjc0LjQxLDEuNzUsMS43NSwwLDAsMS0uNzQtLjQxWiIvPjxwYXRoIGNsYXNzPSJjbHMtNCIgZD0iTTI4LjYyLDcxLjU3QTIuNTIsMi41MiwwLDAsMCwzMiw3MS4xMUw1OS4xMiw0Ni4zNGEzLjQyLDMuNDIsMCwwLDAsMC01TDU4Ljg3LDQxLDI4LjU0LDcxLjQ4WiIvPjxwYXRoIGNsYXNzPSJjbHMtNSIgZD0iTTM0LjQ2LDM0LjcxbC0xMC42LTguNDNhMi42LDIuNiwwLDAsMC00LjIsMi4zM2wuMTksMS42NGExOC4yMSwxOC4yMSwwLDAsMCwxMS42OSwxNWwxMy42OSw1LjE0LDIuMzEtMi41NUwzNi4xNiwzNi43M0ExNi40NSwxNi40NSwwLDAsMSwzNC40NiwzNC43MVoiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik03NC42OSw3NS40MSw2NS44OCw2NS4xMmExNi40NSwxNi40NSwwLDAsMS0yLjA4LTEuNjNMNTIuMzMsNTIuNTVsLTIuNTIsMi4zLDUuNjcsMTMuNThBMTguMjEsMTguMjEsMCwwLDAsNzAuODcsNzkuNTZsMS42NC4xM0EyLjYsMi42LDAsMCwwLDc0LjY5LDc1LjQxWiIvPjxwYXRoIGNsYXNzPSJjbHMtNSIgZD0iTTU4LjY0LDQ2Ljc4YTMsMywwLDAsMCwzLjg1LTIuMTcsMy4yOCwzLjI4LDAsMCwwLTMtNC4xNWgwbC0uNTkuNTloMGwuMjYuMjVhMy40MiwzLjQyLDAsMCwxLDAsNVoiLz48cGF0aCBjbGFzcz0iY2xzLTYiIGQ9Ik0zMi43NywxNy4xOGwtLjUsMS41M2ExNy42LDE3LjYsMCwwLDAsMy44OSwxOEw0Ny41Myw0Ny44MmwzLjYxLTQtMTMuNy0yN0EyLjU0LDIuNTQsMCwwLDAsMzIuNzcsMTcuMThaIi8+PHBhdGggY2xhc3M9ImNscy02IiBkPSJNODMuNjUsNjEuNDgsNTYuMzUsNDguODdsLTQsMy42OEw2My44LDYzLjQ5YTE3LjYsMTcuNiwwLDAsMCwxOC4xNSwzLjIzbDEuNTEtLjU1QTIuNTQsMi41NCwwLDAsMCw4My42NSw2MS40OFoiLz48cGF0aCBjbGFzcz0iY2xzLTYiIGQ9Ik01My41OCw0MS4xN2EzLjcsMy43LDAsMCwxLDUuMjEtLjJsLjA4LjA4aDBsLjU5LS41OWgwYTMuNDEsMy40MSwwLDAsMC00LjI5LTIuOTNjLTIsLjM4LTMuMDcsMi42OC0yLDQuMTFaIi8+PC9nPjwvc3ZnPg==
  introduction: |-
    [Red Hat® JBoss® Enterprise Application Platform (EAP)](https://www.redhat.com/en/technologies/jboss-middleware/application-platform) is an application server. It includes everything needed to build, run, deploy, and manage enterprise Java applications in a variety of environments, including on-premise, virtual environments, and in private, public, and hybrid clouds.

    * **Optimized for OpenShift, Cloud and Containers**

    * **Jakarta EE 8 compatibility**

    * **Lightweight, flexible architecture**

    * **Red Hat Portfolio Integration**

    * **More productive developers with DevOps and Agile Development**

    In this quick start, you will deploy and run a [Jakarta EE application](https://github.com/jboss-eap-up-and-running/eap7-with-postgres) with JBoss EAP 7 using its [datasources feature pack](https://github.com/jbossas/eap-datasources-galleon-pack).

    The datasources feature pack for JBoss EAP and JBoss EAP XP makes it really easy to configure EAP with JDBC drivers and datasources for various databases such as Oracle, MS SQLServer and PostgreSQL.

    The entire application and its resources (EAP and PostgreSQL database) will be deployed using a Helm package.
  prerequisites:
    - You completed the "Get started with JBoss EAP 7 using a Helm Chart" quick start.
  tasks:
    - title: Open The OpenShift Command Line Terminal
      description: >-
        In the top right-hand corner, click on the icon `>_` to open the OpenShift Command Line Terminal.
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: |-
          The OpenShift Command Line Terminal is open in the bottom of the OpenShift Web console.openshift.io/v1

          - Do you see a terminal prompt with the message `Welcome to the OpenShift Web Terminal.`
      summary:
        failed: Try the steps again.
        success: The OpenShift Command Line Terminal is open.
    - title: Install the Application Helm package
      description: >-
        In the OpenShift Command Line Terminal, execute the commands:

        ```
        helm install eap7-with-postgres https://github.com/jmesnil/eap7-with-postgres/raw/helm_application/eap7-with-postgresql-1.0.0.tgz
        ```

        This command will install a Helm package that contains all OpenShift resources that composed the applications. The source code for the Helm package is located at 
        [https://github.com/jmesnil/eap7-with-postgres/tree/helm_application/chart](https://github.com/jmesnil/eap7-with-postgres/tree/helm_application/chart). The `value.yaml` file
        contains the properties to build a JBoss EAP 7 application that connects to PostgreSQL and connect to the database when it is deployed:

        ```
        database:
          name: sampledb
          user: "my-user"
          password: "my-password"
        eap74:
          build:
            uri: https://github.com/jboss-eap-up-and-running/eap7-with-postgres
            s2i:
              featurePacks:
                - org.jboss.eap:eap-datasources-galleon-pack:7.4.0.GA-redhat-00003
              galleonLayers: 
                - cloud-server
                - postgresql-datasource
            env:
              - name: POSTGRESQL_DRIVER_VERSION
                value: '42.2.19'
          deploy:
            env:
              # Env vars to connect to PostgreSQL DB
              - name: POSTGRESQL_DATABASE
                valueFrom:
                  secretKeyRef:
                    key: database-name
                    name: postgresql
              - name: POSTGRESQL_USER
                valueFrom:
                  secretKeyRef:
                    key: database-user
                    name: postgresql
              - name: POSTGRESQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: database-password
                    name: postgresql
              - name: POSTGRESQL_DATASOURCE
                value: qs-ds
              - name: POSTGRESQL_SERVICE_HOST
                value: postgresql
        ```
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: |-
          The Helm package is successfully deployed.

          - Do you see a message in the OpenShift Command Line Terminal with the following information?

            ```
            name: eap7-with-postgres
            STATUS: deployed
            ```
      summary:
        failed: Try the steps again.
        success: Your application with EAP and PostgreSQL has been deployed onto OpenShift.
    - description: >-
        To view the build status of the JBoss EAP 7 application:

        1. In the navigation menu, click [Topology]{{highlight qs-nav-topology}}.

        1. In the Topology view, click **D eap7-with-postgres**.  
           A side panel opens with detailed information about the application.

        1. In the side panel, click the **Resources** tab.  
           The **Builds** section shows all the details related to builds of the application.

        The JBoss EAP 7 application is built in two steps:

          - The first build configuration **eap7-with-postgres-build-artifacts** compiles and packages the Jakarta EE application, and creates a JBoss EAP server.
            The application is run on this JBoss EAP server.

            The build may take a few minutes to complete. The build progresses through various states such as **Pending**, **Running**, and **Complete**.
            The build state is indicated by a relevant message.

            When the build is complete, a checkmark and the following message is displayed: **Build #1 was complete**.

            When the first build is complete, the second build starts.

          - The second build configuration **eap7-with-postgres** puts the Jakarta EE deployment and the JBoss EAP server in a runtime image that contains only what is required to run the  application.

            When the second build is complete, a checkmark and the following message are displayed: **Build #2 was complete**.
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >-
          The two builds for **eap7-with-postgres-build-artifacts** and **eap74** may take a few minutes to complete.

          Verify the builds are complete:

          - The message **Build #1 was complete** is displayed for the **eap7-with-postgres-build-artifacts** build configuration. Did this message appear?

          - The message **Build #2 was complete** is displayed for the **eap7-with-postgres** build configuration. Did this message appear?
      summary:
        failed: Try the steps again.
        success: Your build is complete.
      title: View the Build status
    - description: >-
        To view the PostgreSQL pod status:

        1. In the navigation menu, click [Topology]{{highlight qs-nav-topology}}.

        1. In the **Topology** view, click **DC postgresql**.  
           A side panel opens with detailed information about the application.

        1. In the **Details** tab, hover over the pod to see the pod status in a tooltip.

            - Inside the pod circle, it displays the number of pod.
            - The color of the pod circle indicates the pod status:
              Light blue = **Pending**, Blue = **Not Ready**, Dark blue = **Running**

        **Note:** In the **Topology** view, the dark outer circle indicates the pod status.
      review:
        failedTaskHelp: >-
          This task isn’t verified yet. Try the task again.
        instructions: |-
          Verify you see the *postgresql* pod status:
          
          - Does the text inside the pod cirle display **1 Pod**?

          - When you hover of the pod circle, does it display **1 Running**?
      summary:
        failed: Try the steps again.
        success: Your deployment has one running pod.
      title: View the PostgreSQL Pod status
    - description: >-
        To view the JBoss EAP pod status:

        1. In the navigation menu, click [Topology]{{highlight qs-nav-topology}}.

        1. In the **Topology** view, click **D eap7-with-postgres**.  
           A side panel opens with detailed information about the application.

        1. In the **Details** tab, hover over the pod to see the pod status in a tooltip.

            - Inside the pod circle, it displays the number of pod.
            - The color of the pod circle indicates the pod status:
              Light blue = **Pending**, Blue = **Not Ready**, Dark blue = **Running**

        **Note:** In the **Topology** view, the dark outer circle indicates the pod status.
      review:
        failedTaskHelp: >-
          This task isn’t verified yet. Try the task again.
        instructions: |-
          Verify you see the `eap7-with-postgres` pod status:
          
          - Does the text inside the pod cirle display **1 Pod**?

          - When you hover of the pod circle, does it display **1 Running**?

      summary:
        failed: Try the steps again.
        success: Your deployment has one running pod.
      title: View the JBoss EAP Pod status
    - description: >-
        The external link icon on the top right quadrant of the **eap74-with-postgres** deployment represents the route URL.
        
        1. Click on the external link icon to open the URL and run the application in a new browser tab.

            * The application displays a page that explains the HTTP endpoints provided by the Jakarta EE application as well
              as a form to interactively add items to the database.

      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >-
          Verify your JBoss EAP 7 application is running:

          - Where you able to add items to the database and verify they were returned by the application?
      summary:
        failed: Try the steps again.
        success: Your JBoss EAP 7 application is running.
      title: Run the JBoss EAP 7 application
  conclusion: |-
    Your JBoss EAP 7 application is deployed and ready.
    It uses the PostgreSQL database to store its database.

    The connection to the DB was configured by including the the EAP datasource feature pack and its `postgresql-datasource`
    layer when the application image is built.

    A set of environment variables at deployment time was used to provide the information to connect to the databasee 
    (through its **service** with the expected user credentials).

    You can learn more about [JBoss EAP](https://www.redhat.com/en/technologies/jboss-middleware/application-platform)
    and its [datasources feature pack](https://github.com/jbossas/eap-datasources-galleon-pack).